#!/bin/bash

#PBS -A open

#PBS -l nodes=1:ppn=8

#PBS -l walltime=12:00:00

#PBS -l pmem=12gb

#Get Started

echo "Job started on $(hostname) at $(date)"

module purge
module load anaconda3
source activate qiime2-2022.2

cd /gpfs/group/ltb5167/default/JennHarris/BONCAT_16S

# try decreasing length  to wear 25th percentile drops below 30

qiime dada2 denoise-paired \
    --i-demultiplexed-seqs ./16S.trimmed.primer.qza \
    --p-n-threads 0 \
    --p-trunc-q 2 \
    --p-trunc-len-f 210 \
    --p-trunc-len-r 210 \
    --p-max-ee-f 2 \
    --p-max-ee-r 2 \
    --p-n-reads-learn 1000000 \
    --p-chimera-method consensus \
    --o-table table-dada2.qza \
    --o-representative-sequences ./asvs/trimmed.dada2.qza \
    --o-denoising-stats ./asvs/stats.dada2.qza


echo "finished"